export const COMMERCE_ENTITY_TYPES = {
  CATEGORY: 'CATEGORY',
  PRODUCT: 'PRODUCT',
  INVENTORY: 'INVENTORY',
  CART: 'CART',
  CART_ITEM: 'CART_ITEM',
  ORDER: 'ORDER',
  ORDER_ITEM: 'ORDER_ITEM',
  USER_PROFILE: 'USER_PROFILE',
} as const

export const COMMERCE_INDEXES = {
  PRODUCT_LIST: 'GSI1',
  CUSTOMER_ORDERS: 'GSI2',
  ORDER_STATUS: 'GSI3',
  CUSTOMER_EMAIL_ORDERS: 'GSI4',
  ORDER_PAYMENT_STATUS: 'GSI5',
  INVENTORY_LIST: 'GSI6',
} as const

export const COMMERCE_GSI_KEYS = {
  PRODUCT_LIST_PK: 'PRODUCT',
  INVENTORY_LIST_PK: 'INVENTORY',
} as const

export const COMMERCE_TABLE_FALLBACK = 'ecommerce'
