import { Transform } from 'class-transformer'
import { IsOptional, IsString, Matches, MaxLength, ValidateIf } from 'class-validator'
import { ApiPropertyOptional } from '@nestjs/swagger'

const trimString = ({ value }: { value: unknown }): unknown =>
  typeof value === 'string' ? value.trim() : value

export class UpdateUserProfileDto {
  @ApiPropertyOptional({ example: 'Nguyen Van A' })
  @IsOptional()
  @Transform(trimString)
  @IsString()
  @MaxLength(120)
  name?: string

  @ApiPropertyOptional({
    example: 'users/0f3e/avatar/a1f2-avatar.webp',
    nullable: true,
    description: 'Set to null to remove the current avatar.',
  })
  @ValidateIf((_, value) => value !== undefined && value !== null)
  @Transform(trimString)
  @IsString()
  @MaxLength(1024)
  @Matches(/^users\/[^/]+\/avatar\/[^/]+$/, {
    message: 'avatarKey must be an avatar key generated by /upload/presign.',
  })
  avatarKey?: string | null
}
